### ISSUE TITLE
[Bug] Handling cli input experiment names

### ISSUE THREAD

**Issue by yhna940** [SIAnalytics/siatune#136]
https://github.com/SIAnalytics/siatune/blob/9a70d11e20eacb05fd01ad08826dc59bce78c72f/siatune/run.py#L48

**Comment by KKIEEK** [comment]
https://github.com/SIAnalytics/siatune/blob/13cf8db692745960c3a1f9c252beb56390ed1f1d/siatune/tune/tuner.py#L41-L42

**Comment by KKIEEK** [comment]
https://github.com/open-mmlab/mmengine/blob/main/mmengine/runner/runner.py#L457
