### ISSUE TITLE
[Refact] Register the scheduling technique explicitly

### ISSUE THREAD

**Issue by yhna940** [SIAnalytics/siatune#82]
https://github.com/SIAnalytics/siatune/blob/647761f3373a6e6a2efac8ff5ed95817a50a5dc6/siatune/ray/schedulers/builder.py#L7

**Comment by KKIEEK** [comment]
I think that code is not too bad. There is a similar [example](https://github.com/open-mmlab/mmengine/blob/601db12d38245140775ed189fcc3b4815843b567/mmengine/optim/optimizer/builder.py#L15-L33).
